### ISSUE TITLE
error: package `wastebin v2.3.3 (/app)` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0

### ISSUE THREAD

**Issue by berezovskyi** [matze/wastebin#31]
The Dockerfile seems to be out of sync.

P.S. Is there a plan for a regular publication of the Docker images on Dockerhub?

**Comment by matze** [comment]
> P.S. Is there a plan for a regular publication of the Docker images on Dockerhub?

I publish a new image whenever I make a new release. I don't think it's worth the time and space to publish one in between.

> may I ask for a tl;dr as to why the latest Rust compiler becomes a build requirement just 26 days after a release?

First, because it's a binary application so there are no downstream dependants I have to care for other than users. Second,  installing an up-to-date Rust toolchain is not a huge hassle with rustup.

In this particular case, I wanted to use Rust 1.70's newly stabilized `once_cell` module in order to get rid of a third-party dependency. Pros and cons as far as I can see.
